# Generated by Django 4.2.2 on 2023-07-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("carts", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(related_name="product", to="products.product"),
        ),
    ]
