# Generated by Django 4.2.2 on 2023-07-04 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ManyToManyField(
                related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
