# Generated by Django 4.2.2 on 2023-07-04 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_image_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.AddField(
            model_name="cart",
            name="product",
            field=models.ManyToManyField(related_name="product", to="products.product"),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ManyToManyField(
                related_name="cart", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
