# Generated by Django 4.2.2 on 2023-07-04 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("carts", "0004_remove_cart_product_remove_cart_user_cart_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ManyToManyField(
                related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
