# Generated by Django 4.2.2 on 2023-07-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_remove_cart_product_remove_cart_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="products",
            new_name="product",
        ),
        migrations.AlterField(
            model_name="cartproducts",
            name="quantity",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
