# Generated by Django 4.2.2 on 2023-07-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("realizado", "Realizado"),
                            ("em andamento", "Em Andamento"),
                            ("concluido", "Concluido"),
                        ],
                        default="realizado",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("seller", models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="RequestProducts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1, null=True)),
                ("seller", models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
