# Generated by Django 4.2.2 on 2023-07-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
